@extends('layouts.app')
@section('title','Мониторинг')
@section('breadcrumb','Мониторинг')
@section('topbar-actions')<a class="secondary-button" href="{{ route('requests.index',request()->query()) }}">Реестр</a><a class="secondary-button" href="{{ route('requests.export',request()->query()) }}">Excel</a>@endsection
@section('content')
<section class="page-title compact-title"><div><h1>Реклама объектлари мониторинги</h1><p>{{ number_format($totals['count'],0,'.',' ') }} та объект, жами {{ number_format($totals['total_area'],2,'.',' ') }} м²</p></div></section>
<section class="metrics monitoring-metrics"><article class="metric-card"><span>Жами объект</span><strong>{{ number_format($totals['count'],0,'.',' ') }}</strong><small>Танланган фильтрлар бўйича</small></article><article class="metric-card"><span>Жами реклама майдони</span><strong>{{ number_format($totals['total_area'],2,'.',' ') }}</strong><small>м²</small></article><article class="metric-card"><span>Фаол туманлар</span><strong>{{ number_format($totals['districts'],0,'.',' ') }}</strong><small>Объект киритилган туманлар</small></article></section>
<section class="panel table-panel registry-card"><div class="table-card-heading"><h2>Туманлар кесимида</h2><span>{{ $rows->count() }} та туман</span></div><div class="table-wrap"><table class="registry-table monitoring-table"><thead><tr><th>Туман</th><th>Объектлар</th><th>Майдон</th><th>Тасдиқланган</th><th>Кўриш</th></tr></thead><tbody>@forelse($rows as $row)<tr class="clickable-row" onclick="window.location='{{ $row['url'] }}'"><td><strong>{{ $row['district']->name }}</strong></td><td>{{ $row['count'] }}</td><td>{{ number_format($row['total_area'],2,'.',' ') }} м²</td><td>{{ $row['statuses']['approved']??0 }}</td><td><a class="row-link" href="{{ $row['url'] }}">Рўйхат</a></td></tr>@empty<tr><td colspan="5" class="empty">Маълумот топилмади.</td></tr>@endforelse</tbody></table></div></section>
@endsection
