@extends('layouts.app')
@php
 $statusLabels=['draft'=>'Қоралама','submitted'=>'Юборилган','in_review'=>'Кўриб чиқилмоқда','approved'=>'Тасдиқланган','rejected'=>'Рад этилган'];
 $ownerTypes=['jismoniy'=>'Жисмоний шахс','yuridik'=>'Юридик шахс']; $display=fn($v)=>filled($v)?$v:'-'; $yesNo=fn($v)=>$v?'Ҳа':'Йўқ';
 $fileLabels=['warning_letter_file'=>'Огоҳлантириш хати','lease_document_file'=>'Ижарага олиш ҳужжати'];
 $auditLabels=['advertising_type'=>'Конструкция тури','advertising_sides'=>'Реклама томонлари','has_passport'=>'Паспорт мавжуд','passport_details'=>'Паспорт маълумотлари','contract_number'=>'Шартнома','contract_amount'=>'Шартнома суммаси','owner_name'=>'Эгаси номи','owner_stir_pinfl'=>'СТИР/ЖШШИР','director_name'=>'Раҳбари','phone_number'=>'Телефони','area_length'=>'Узунлик','area_width'=>'Кенглик','total_area'=>'Майдони','latitude'=>'Кенглик координатаси','longitude'=>'Узунлик координатаси','status'=>'Ҳолати'];
@endphp
@section('title',$requestItem->request_number)
@section('breadcrumb','Реклама объектлари')
@section('content')
<section class="page-title compact-title"><div><h1>{{ $requestItem->request_number }}</h1><p>{{ $requestItem->district->name }}, {{ $requestItem->mahalla->name }}, {{ $requestItem->street->name }}, {{ $requestItem->house_number }}</p></div><div class="title-actions"><span class="status {{ $requestItem->status }}">{{ $statusLabels[$requestItem->status]??$requestItem->status }}</span>@can('update',$requestItem)<a class="secondary-button" href="{{ route('requests.edit',$requestItem) }}">Таҳрирлаш</a>@endcan @can('delete',$requestItem)<form method="POST" action="{{ route('requests.destroy',$requestItem) }}" onsubmit="return confirm('Ўчиришни тасдиқлайсизми?')">@csrf @method('DELETE')<button class="danger-button">Ўчириш</button></form>@endcan</div></section>
<section class="registry-card form-panel readonly-request">
 <div class="stepper">@foreach(['Эгаси','Манзил','Ўлчам','Харита','Файллар'] as $i=>$v)<button class="step {{ $i===0?'active':'' }}" type="button" data-step-target="{{ $i+1 }}">{{ $i+1 }}. {{ $v }}</button>@endforeach</div>
 <section class="form-step-panel active" data-step-panel="1"><div class="form-section"><h2>Эгаси</h2><div class="form-grid two">
  @foreach(['Эгаси тури'=>$ownerTypes[$requestItem->owner_type]??$requestItem->owner_type,'Эгасининг номи'=>$requestItem->owner_name,'СТИР / ЖШШИР'=>$requestItem->owner_stir_pinfl,'Раҳбари'=>$requestItem->director_name,'Телефони'=>$requestItem->phone_number,'Яратувчи'=>$requestItem->creator->name] as $k=>$v)<div class="readonly-field"><span>{{ $k }}</span><strong>{{ $display($v) }}</strong></div>@endforeach
 </div></div></section>
 <section class="form-step-panel" data-step-panel="2"><div class="form-section"><h2>Манзил</h2><div class="form-grid two">@foreach(['Туман'=>$requestItem->district->name,'Маҳалла'=>$requestItem->mahalla->name,'Кўча тури'=>\App\Models\RegistryRequest::STREET_TYPES[$requestItem->street_type]??$requestItem->street_type,'Кўча номи'=>$requestItem->street->name,'Уй рақами'=>$requestItem->house_number] as $k=>$v)<div class="readonly-field"><span>{{ $k }}</span><strong>{{ $display($v) }}</strong></div>@endforeach</div></div></section>
 <section class="form-step-panel" data-step-panel="3"><div class="form-section"><h2>Ўлчам ва конструкция</h2><div class="form-grid two">@foreach(['Конструкция тури'=>\App\Models\RegistryRequest::ADVERTISING_TYPES[$requestItem->advertising_type]??$requestItem->advertising_type,'Узунлик (м)'=>$requestItem->area_length,'Кенглик (м)'=>$requestItem->area_width,'Майдони (м²)'=>$requestItem->total_area,'Реклама томонлари'=>$requestItem->advertising_sides,'Паспорт мавжудми?'=>$yesNo($requestItem->has_passport),'Паспорт маълумотлари'=>$requestItem->passport_details,'Шартномаси'=>$requestItem->contract_number,'Шартнома суммаси'=>$requestItem->contract_amount] as $k=>$v)<div class="readonly-field"><span>{{ $k }}</span><strong>{{ $display($v) }}</strong></div>@endforeach</div></div></section>
 <section class="form-step-panel" data-step-panel="4"><div class="form-section"><h2>Харита</h2><div id="show-map" class="leaflet-map" data-point='@json([$requestItem->latitude,$requestItem->longitude])'></div><div class="form-grid two"><div class="readonly-field"><span>Кенглик</span><strong>{{ $requestItem->latitude }}</strong></div><div class="readonly-field"><span>Узунлик</span><strong>{{ $requestItem->longitude }}</strong></div></div></div></section>
 <section class="form-step-panel" data-step-panel="5"><div class="form-section"><h2>Файллар</h2>@if($requestItem->images->isNotEmpty())<div class="readonly-media-grid">@foreach($requestItem->images as $image)<a class="readonly-media-card" href="{{ Storage::url($image->path) }}" target="_blank"><img src="{{ Storage::url($image->path) }}"><span>{{ $image->original_name }}</span></a>@endforeach</div>@endif<div class="document-grid readonly-documents">@foreach($requestItem->files as $file)<a href="{{ Storage::url($file->path) }}" target="_blank">{{ $fileLabels[$file->type]??$file->type }}: {{ $file->original_name }}</a>@endforeach</div></div>
  <div class="form-section"><h2>Ўзгаришлар тарихи</h2>@if($requestItem->audits->isEmpty())<div class="empty-inline">Ўзгаришлар тарихи йўқ.</div>@else<ol class="timeline">@foreach($requestItem->audits as $audit)<li><div class="timeline-head"><strong>{{ $audit->user?->name??'Тизим' }}</strong><span>{{ $audit->created_at->format('d.m.Y H:i') }}</span></div><p>{{ $audit->event }}</p>@php($keys=array_intersect(array_unique(array_merge(array_keys($audit->old_values??[]),array_keys($audit->new_values??[]))),array_keys($auditLabels)))@foreach($keys as $key)<div class="audit-change"><strong>{{ $auditLabels[$key] }}</strong><span>Олдин: {{ data_get($audit->old_values,$key,'-') }}</span><span>Кейин: {{ data_get($audit->new_values,$key,'-') }}</span></div>@endforeach</li>@endforeach</ol>@endif</div>
 </section>
</section>
@endsection
